# Generated by Django 5.2.15 on 2026-08-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freddyfazbearPizzaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='animatronic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
