# Generated by Django 5.2.15 on 2026-08-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freddyfazbearPizzaria', '0002_animatronic'),
    ]

    operations = [
        migrations.AddField(
            model_name='animatronic',
            name='battery_level',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='animatronic',
            name='servo_health',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='animatronic',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
